; song ids
; Music indexes (see audio/music_pointers.asm)
	const_def
	const MUSIC_NONE                         ; 00
	const MUSIC_PALLET_TOWN                  ; 01
	const MUSIC_POKECENTER                   ; 02
	const MUSIC_GYM                          ; 03
	const MUSIC_CITIES1                      ; 04
	const MUSIC_CITIES2                      ; 05
	const MUSIC_CELADON                      ; 06
	const MUSIC_CINNABAR                     ; 07
	const MUSIC_VERMILION                    ; 08
	const MUSIC_LAVENDER                     ; 09
	const MUSIC_SS_ANNE                      ; 0a
	const MUSIC_MEET_PROF_OAK                ; 0b
	const MUSIC_MEET_RIVAL                   ; 0c
	const MUSIC_RIVAL_AFTER					 ; 0d
	const MUSIC_MUSEUM_GUY                   ; 0e
	const MUSIC_SAFARI_ZONE                  ; 0f
	const MUSIC_PKMN_HEALED                  ; 10
	const MUSIC_ROUTES1                      ; 11
	const MUSIC_ROUTES2                      ; 12
	const MUSIC_ROUTES3                      ; 13
	const MUSIC_ROUTES4                      ; 14
	const MUSIC_INDIGO_PLATEAU               ; 15
	const MUSIC_GYM_LEADER_BATTLE            ; 16
	const MUSIC_TRAINER_BATTLE               ; 17
	const MUSIC_WILD_BATTLE                  ; 18
	const MUSIC_FINAL_BATTLE                 ; 19
	const MUSIC_DEFEATED_TRAINER             ; 1a
	const MUSIC_DEFEATED_WILD_MON            ; 1b
	const MUSIC_DEFEATED_GYM_LEADER          ; 1c
	const MUSIC_TITLE_SCREEN                 ; 1d
	const MUSIC_CREDITS                      ; 1e
	const MUSIC_HALL_OF_FAME                 ; 1f
	const MUSIC_OAKS_LAB                     ; 20
	const MUSIC_JIGGLYPUFF_SONG              ; 21
	const MUSIC_BIKE_RIDING                  ; 22
	const MUSIC_SURFING                      ; 23
	const MUSIC_GAME_CORNER                  ; 24
	const MUSIC_INTRO_BATTLE                 ; 25
	const MUSIC_DUNGEON1                     ; 26
	const MUSIC_DUNGEON2                     ; 27
	const MUSIC_DUNGEON3                     ; 28
	const MUSIC_CINNABAR_MANSION             ; 29
	const MUSIC_POKEMON_TOWER                ; 2a
	const MUSIC_SILPH_CO                     ; 2b
	const MUSIC_MEET_EVIL_TRAINER            ; 2c
	const MUSIC_MEET_FEMALE_TRAINER          ; 2d
	const MUSIC_MEET_MALE_TRAINER            ; 2e
	const MUSIC_SURFING_PIKACHU              ; 2f
	const MUSIC_YELLOW_UNUSED_SONG           ; 30
	const MUSIC_GB_PRINTER                   ; 31
	const MUSIC_CITY_SLOW					 ; 32
	const MUSIC_MEET_RIVAL_2				 ; 33
	const MUSIC_RIVAL_AFTER_2				 ; 34
	const MUSIC_AZALEA_TOWN                  ; 35
	const MUSIC_CHERRYGROVE_CITY             ; 36
	const MUSIC_KIMONO_ENCOUNTER             ; 37
	const MUSIC_UNION_CAVE                   ; 38
	const MUSIC_JOHTO_WILD_BATTLE            ; 39
	const MUSIC_VIOLET_CITY                  ; 3a
	const MUSIC_ROCKET_BATTLE                ; 3b
	const MUSIC_DARK_CAVE                    ; 3c
	const MUSIC_ROCKET_ENCOUNTER             ; 3d
	const MUSIC_SAGE_ENCOUNTER               ; 3e
	const MUSIC_LAKE_OF_RAGE                 ; 3f
	const MUSIC_JOHTO_WILD_BATTLE_NIGHT      ; 40
	const MUSIC_CAPTURE						 ; 41
	const MUSIC_VICTORY_ROAD				 ; 42
	const MUSIC_RUINS_OF_ALPH_INTERIOR       ; 43
	const MUSIC_BATTLE_TOWER_THEME           ; 44
	const MUSIC_SUICUNE_BATTLE               ; 45
	const MUSIC_BATTLE_TOWER_LOBBY           ; 46
	const MUSIC_MOBILE_CENTER                ; 47
	const MUSIC_FARAWAY_ISLAND               ; 48
DEF NUM_MUSIC_SONGS EQU const_value
