; SFX indexes (see audio/sfx_pointers.asm)
	const_def
	const SFX_GET_ITEM_1                  ; 00
	const SFX_LEVEL_UP                    ; 01
	const SFX_GET_ITEM_2                  ; 02
	const SFX_TINK                        ; 03
	const SFX_HEAL_HP                     ; 04
	const SFX_HEAL_AILMENT                ; 05
	const SFX_START_MENU                  ; 06
	const SFX_PRESS_AB                    ; 07
	const SFX_POKEDEX_RATING              ; 09
	const SFX_GET_KEY_ITEM                ; 0a
	const SFX_POISONED                    ; 0b
	const SFX_TRADE_MACHINE               ; 0c
	const SFX_TURN_ON_PC                  ; 0d
	const SFX_TURN_OFF_PC                 ; 0e
	const SFX_ENTER_PC                    ; 0f
	const SFX_SHRINK                      ; 10
	const SFX_SWITCH                      ; 11
	const SFX_HEALING_MACHINE             ; 12
	const SFX_TELEPORT_EXIT_1             ; 13
	const SFX_TELEPORT_ENTER_1            ; 14
	const SFX_TELEPORT_EXIT_2             ; 15
	const SFX_LEDGE                       ; 16
	const SFX_TELEPORT_ENTER_2            ; 17
	const SFX_FLY                         ; 18
	const SFX_DENIED                      ; 19
	const SFX_ARROW_TILES                 ; 1a
	const SFX_PUSH_BOULDER                ; 1b
	const SFX_SS_ANNE_HORN                ; 1c
	const SFX_WITHDRAW_DEPOSIT            ; 1d
	const SFX_CUT_HM                	  ; 1e
	const SFX_GO_INSIDE                   ; 1f
	const SFX_SWAP                        ; 20
	const SFX_TALLY                       ; 21
	const SFX_PURCHASE                    ; 22
	const SFX_GO_OUTSIDE                  ; 23
	const SFX_COLLISION                   ; 24
	const SFX_SAVE                        ; 25
	const SFX_POKEFLUTE                   ; 26
	const SFX_SAFARI_ZONE_PA              ; 27
	const SFX_BALL_TOSS                   ; 28
	const SFX_BALL_POOF                   ; 29
	const SFX_FAINT_THUD                  ; 2a
	const SFX_RUN                         ; 2b
	const SFX_DEX_PAGE_ADDED              ; 2c
	const SFX_CAUGHT_MON                  ; 2d
	const SFX_PECK                        ; 2e
	const SFX_KINESIS                     ; 2f
	const SFX_LICK                        ; 30
	const SFX_POUND                       ; 31
	const SFX_THRASH                      ; 32
	const SFX_COMET_PUNCH                 ; 33
	const SFX_MEGA_PUNCH                  ; 34
	const SFX_SCRATCH                     ; 35
	const SFX_VICEGRIP                    ; 36
	const SFX_RAZOR_WIND                  ; 37
	const SFX_CUT                         ; 38
	const SFX_WING_ATTACK                 ; 39
	const SFX_WHIRLWIND                   ; 3a
	const SFX_BIND                        ; 3b
	const SFX_VINE_WHIP                   ; 3c
	const SFX_DOUBLE_KICK                 ; 3d
	const SFX_MEGA_KICK                   ; 3e
	const SFX_HEADBUTT                    ; 3f
	const SFX_HORN_ATTACK                 ; 40
	const SFX_TACKLE                      ; 41
	const SFX_POISON_STING                ; 42
	const SFX_POWDER                      ; 43
	const SFX_DOUBLESLAP                  ; 44
	const SFX_BITE                        ; 45
	const SFX_JUMP_KICK                   ; 46
	const SFX_STOMP                       ; 47
	const SFX_TAIL_WHIP                   ; 48
	const SFX_KARATE_CHOP                 ; 49
	const SFX_SUBMISSION                  ; 4a
	const SFX_WATER_GUN                   ; 4b
	const SFX_SWORDS_DANCE                ; 4c
	const SFX_THUNDER                     ; 4d
	const SFX_SUPERSONIC                  ; 4e
	const SFX_LEER                        ; 4f
	const SFX_EMBER                       ; 50
	const SFX_BUBBLEBEAM                  ; 51
	const SFX_HYDRO_PUMP                  ; 52
	const SFX_SURF                        ; 53
	const SFX_PSYBEAM                     ; 54
	const SFX_CHARGE                      ; 55
	const SFX_THUNDERSHOCK                ; 56
	const SFX_PSYCHIC                     ; 57
	const SFX_SCREECH                     ; 58
	const SFX_BONE_CLUB                   ; 59
	const SFX_SHARPEN                     ; 5a
	const SFX_EGG_BOMB                    ; 5b
	const SFX_SING                        ; 5c
	const SFX_HYPER_BEAM                  ; 5d
	const SFX_SILPH_SCOPE                 ; 5e
	const SFX_INTRO_LUNGE                 ; 5f
	const SFX_SWITCH_POCKETS              ; 60
	const SFX_INTRO_RAISE                 ; 61
	const SFX_INTRO_CRASH                 ; 62
	const SFX_SLOTS_STOP_WHEEL            ; 63
	const SFX_SLOTS_REWARD                ; 64
	const SFX_SLOTS_NEW_SPIN              ; 65
	const SFX_METRONOME                   ; 66
	const SFX_SANDSTORM                   ; 67
	const SFX_ELEVATOR                    ; 68
	const SFX_PROTECT                     ; 69
	const SFX_SKETCH                      ; 6a
	const SFX_RAIN_DANCE                  ; 6b
	const SFX_AEROBLAST                   ; 6c
	const SFX_SPARK                       ; 6d
	const SFX_CURSE                       ; 6e
	const SFX_RAGE                        ; 6f
	const SFX_THIEF                       ; 70
	const SFX_THIEF_2                     ; 71
	const SFX_SPIDER_WEB                  ; 72
	const SFX_MIND_READER                 ; 73
	const SFX_NIGHTMARE                   ; 74
	const SFX_SNORE                       ; 75
	const SFX_SWEET_KISS                  ; 76
	const SFX_SWEET_KISS_2                ; 77
	const SFX_BELLY_DRUM                  ; 78
	const SFX_TOXIC                       ; 79
	const SFX_SLUDGE_BOMB                 ; 7a
	const SFX_FORESIGHT                   ; 7b
	const SFX_SPITE                       ; 7c
	const SFX_OUTRAGE                     ; 7d
	const SFX_PERISH_SONG                 ; 7e
	const SFX_GIGA_DRAIN                  ; 7f
	const SFX_ATTRACT                     ; 80
	const SFX_KINESIS_2                   ; 81
	const SFX_ZAP_CANNON                  ; 82
	const SFX_MEAN_LOOK                   ; 83
	const SFX_HEAL_BELL                   ; 84
	const SFX_RETURN                      ; 85
	const SFX_EXP_BAR                     ; 86
	const SFX_MILK_DRINK                  ; 87
	const SFX_PRESENT                     ; 88
	const SFX_MORNING_SUN                 ; 89
	const SFX_KEY_ITEM_2                  ; 8a
	const SFX_GET_EGG                     ; 8b
	const SFX_MOVE_DELETED                ; 8c
	const SFX_CHOOSE_A_CARD               ; 8d
	const SFX_GET_TM                      ; 8e
	const SFX_GET_BADGE                   ; 8f
	const SFX_QUIT_SLOTS                  ; 90
	const SFX_EGG_CRACK                   ; 91
	const SFX_DEX_FANFARE_LESS_THAN_20    ; 92
	const SFX_DEX_FANFARE_140_169         ; 93
	const SFX_DEX_FANFARE_170_199         ; 94
	const SFX_DEX_FANFARE_200_229         ; 95
	const SFX_DEX_FANFARE_230_PLUS        ; 96
	const SFX_EVOLVED                     ; 97
	const SFX_MASTER_BALL                 ; 98
	const SFX_EGG_HATCH                   ; 99
	const SFX_FLASH                       ; 9a
	const SFX_SHOOTING_STAR               ; 9b
	const SFX_NOT_VERY_EFFECTIVE          ; 9c
	const SFX_DAMAGE                      ; 9d
	const SFX_SUPER_EFFECTIVE             ; 9e
	const SFX_BALL_BOUNCE                 ; 9f
	const SFX_MOONLIGHT                   ; a0
	const SFX_ENCORE                      ; a1
	const SFX_BEAT_UP                     ; a2
	const SFX_BATON_PASS                  ; a3
	const SFX_BALL_WOBBLE                 ; a4
	const SFX_SWEET_SCENT                 ; a5
	const SFX_SWEET_SCENT_2               ; a6
	const SFX_HIT_END_OF_EXP_BAR          ; a7
	const SFX_GIVE_TRADEMON               ; a8
	const SFX_GET_TRADEMON                ; a9
	const SFX_2_BOOPS                     ; aa
	const SFX_TWINKLE                     ; ab
	const SFX_INTRO_HIP                   ; ac
	const SFX_INTRO_HOP                   ; ad
	const SFX_INTRO_WHOOSH                ; ae
	const SFX_SURFING_JUMP                ; af
	const SFX_SURFING_FLIP                ; b0
	const SFX_SURFING_CRASH               ; b1
	const SFX_SURFING_LAND                ; b2
	const SFX_POKEFLUTE_2				  ; b3
DEF NUM_SFX EQU const_value
