; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	table_width 3, Music
	dba Music_Nothing
	dba Music_PalletTown
	dba Music_PokemonCenter
	dba Music_Gym
	dba Music_ViridianCity
	dba Music_GoldenrodCity
	dba Music_CeladonCity
	dba Music_EcruteakCity
	dba Music_VermilionCity	
	dba Music_LavenderTown	
	dba Music_SSAqua	
	dba Music_ProfOak
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_ShowMeAround
	dba Music_Evolution
	dba Music_HealPokemon
	dba Music_Route1
	dba Music_Route30
	dba Music_Route3
	dba Music_Route12
	dba Music_IndigoPlateau
	dba Music_KantoGymBattle
	dba Music_KantoTrainerBattle
	dba Music_KantoWildBattle
	dba Music_ChampionBattle
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_TitleScreen
	dba Music_Credits
	dba Music_HallOfFame
	dba Music_ProfOaksPokemonTalk
	dba Music_MagnetTrain
	dba Music_Bicycle
	dba Music_Surf
	dba Music_GameCorner
	dba Music_GoldSilverOpening2
	dba Music_RocketHideout
	dba Music_Route2
	dba Music_MtMoon
	dba Music_BurnedTower
	dba Music_SproutTower
	dba Music_RocketTheme	
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookOfficer
	dba Music_MobileAdapterMenu
	dba Music_LookMysticalMan
	dba Music_Printer	
	dba Music_ViridianCity
	dba Music_LookRival
	dba Music_AfterTheRivalFight	
	dba Music_AzaleaTown
	dba Music_CherrygroveCity
	dba Music_LookKimonoGirl
	dba Music_UnionCave
	dba Music_JohtoWildBattle
	dba Music_VioletCity
	dba Music_RocketBattle
	dba Music_DarkCave
	dba Music_LookRocket
	dba Music_LookSage
	dba Music_LakeOfRage
	dba Music_JohtoWildBattleNight
	dba Music_SuccessfulCapture
	dba Music_VictoryRoad
	dba Music_RuinsOfAlphInterior
	dba Music_BattleTowerTheme
	dba Music_SuicuneBattle
	dba Music_BattleTowerLobby
	dba Music_MobileCenter
	dba Music_Lighthouse
	assert_table_length NUM_MUSIC_SONGS
